# Generated by Django 3.2.3 on 2021-05-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas_plásticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Precio', models.FloatField()),
                ('Días_de_entrega', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Estanterías',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Precio', models.FloatField()),
                ('Días_de_entrega', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lockers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Precio', models.FloatField()),
                ('Días_de_entrega', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Muebles_de_oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Precio', models.FloatField()),
                ('Días_de_entrega', models.CharField(max_length=60)),
            ],
        ),
    ]
